### ISSUE TITLE
Disable MessageSourceHelper in config

### ISSUE THREAD

**Issue by smozely** [allegro/handlebars-spring-boot-starter#11]
This might be a simple question.

I want to disable the MessageSourceHelper, because I don't use it and the name message clashes with then name message I use in my domain model (as well as the message property when writing a error handler for development)

Wondering if there is already a way to do this ... Searching through the code I can't see it

**Comment by plesiecki** [comment]
Hello,

Well, right now there is no way to do this from the properties level but it seems reasonable and relatively easy because HandlebarsViewResolver has methods like setRegisterMessageHelper/withoutMessageHelper. Maybe you would like to make a proposal in form of a pull request?

**Comment by smozely** [comment]
Yip I'll do that ... Just wanted to check I wasn't missing something before attacking that. 

Thinking that I'll add it into the HandlebarsProperties and then set it on the view resolver form there. Sound about right?

**Comment by plesiecki** [comment]
Sure!

**Comment by plesiecki** [comment]
fixed in 0.2.4

**Comment by smozely** [comment]
Great thanks, sorry I never found time to do the fix myself

**Comment by plesiecki** [comment]
No problem. Thanks for pointing it out
