### ISSUE TITLE
How to extend context stack?

### ISSUE THREAD

**Issue by cabrilo** [allegro/handlebars-spring-boot-starter#13]
Hello,

I just started using handlebars-spring-boot-starter and thank you for your hard work. The project is very useful and I hope it ends up among official spring boot starters.

Handlebars.java documentations describes how to hook into context stack here: https://github.com/jknack/handlebars.java/blob/master/README.md#user-content-extending-the-context-stack

They say hookContextStack is dependent on implementation, so I was wandering, what would be the correct way to do hookContextStack when using handlebars-spring-boot-starter? 

Essentially, my goal is to pass same data to all views - so if there is an alternative way, I'd be happy to hear it as well.

Thanks!
Dejan

**Comment by plesiecki** [comment]
Hello!

First of all, thank you for your kind words. 
Honestly I've never used this feature. I will need some time for exploration.
Please stay tuned for updates.

**Comment by platan** [comment]
handlebars-spring-boot-starter uses [handlebars-springmvc](https://github.com/jknack/handlebars.java#springmvc) for integration between Spring MVC and Handlebars.java. I think that [HandlebarsView#renderMergedTemplateModel](https://github.com/jknack/handlebars.java/blob/master/handlebars-springmvc/src/main/java/com/github/jknack/handlebars/springmvc/HandlebarsView.java#L58) method is the `hookContextStack` method. 

If you want pass same data to all views (controllers) you can use [HandlerInterceptor](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/HandlerInterceptor.html).

Here you can find more information how to do it:
- http://stackoverflow.com/questions/7360784/add-attributes-to-the-model-of-all-controllers-in-spring-3
- http://stackoverflow.com/questions/10391988/in-spring-3-1-can-mvcinterceptors-be-used-in-conjunction-with-configuration
- http://stackoverflow.com/questions/23349180/java-config-for-spring-interceptor-where-interceptor-is-using-autowired-spring-b
- http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-handlermapping-interceptor

**Comment by cabrilo** [comment]
@platan Thanks. I think HandlerInterceptor would be the way to go.
