### ISSUE TITLE
Update Handlebars.java version

### ISSUE THREAD

**Issue by pacey** [allegro/handlebars-spring-boot-starter#15]
It would be awesome to update the Handlebars.java version to 4.0.0 that was released a few days ago. I'd be happy to do it myself if you could point me in the right direction!

**Comment by platan** [comment]
Version [0.2.8](http://search.maven.org/#artifactdetails|pl.allegro.tech.boot|handlebars-spring-boot-starter|0.2.8|) released few days ago has Handlebars.java version 4.0.0.

**Comment by pacey** [comment]
Lovely, thanks!

**Comment by plesiecki** [comment]
Please don't forget to star our repo. Happy coding!
