### ISSUE TITLE
Version-update to current handlebars-java library

### ISSUE THREAD

**Issue by Arkinator** [allegro/handlebars-spring-boot-starter#21]
He,
we use this project for a big product, so first of all: Thanks for your work :)
We would like to update from our current version 2.10 (which uses the 4.0.2 jknack), but would much rather you pushed out a new version using the current jknack 4.0.6 then use your version 0.2.12, which in turn references jknack 4.0.4.

TL;DR: Please publish a new version using the current version of com.github.jknack

**Comment by DracoBlue** [comment]
Done with #22 in 0.2.13
