### ISSUE TITLE
StringHelper not included by default

### ISSUE THREAD

**Issue by hainesr** [allegro/handlebars-spring-boot-starter#25]
With other helpers that you can specify in the Maven dependencies, e.g. Markdown helper, this starter will automatically register the helpers. But the included String helpers are not automatically registered.

Would it be possible to automatically register the String helpers?

**Comment by hainesr** [comment]
Just trying to debug this, as I have found the `HandlebarsHelpersAutoConfiguration` class, and it looks like it should register the `StringHelpers` class automatically.

My code:
```java
@Autowired
private HandlebarsViewResolver htmlResolver;

<snip>

for (Entry<String, Helper<?>> e : htmlResolver.helpers()) {
  System.out.println("Helper: " + e.getKey());
}
```

Outputs:
```
Helper: message
Helper: i18nJs
Helper: with
Helper: unless
Helper: if
Helper: i18n
Helper: block
Helper: precompile
Helper: each
Helper: partial
Helper: log
Helper: lookup
Helper: embedded
```

So none of the helpers in `StringHelpers` are there. Explicitly registering the `StringHelpers` class gives:
```
Helper: lower
Helper: wordWrap
Helper: block
Helper: lookup
Helper: center
Helper: upper
Helper: slugify
Helper: rjust
Helper: unless
Helper: if
Helper: substring
Helper: dateFormat
Helper: stripTags
Helper: with
Helper: abbreviate
Helper: yesno
Helper: capitalize
Helper: capitalizeFirst
Helper: join
Helper: partial
Helper: defaultIfEmpty
Helper: log
Helper: embedded
Helper: ljust
Helper: replace
Helper: message
Helper: i18nJs
Helper: now
Helper: numberFormat
Helper: i18n
Helper: stringFormat
Helper: precompile
Helper: each
Helper: cut
```

Am I missing something? I'm guessing that this isn't the expected behaviour but I don't understand enough about how Spring Boot does its magic to debug any further.

I've got a standard Spring Boot application with spring-webmvc on the classpath so `@ConditionalOnWebApplication` should (?) fire correctly.

**Comment by platan** [comment]
Hi. Sorry for late reply. Unfortunately we've missed this issue. 
It seems that handlebars-spring-boot-starter version 0.2.15 registers [String helpers](https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java). There is a [test](https://github.com/allegro/handlebars-spring-boot-starter/blob/master/src/test/groovy/pl/allegro/tech/boot/autoconfigure/handlebars/HandlebarsHelpersAutoConfigurationSpec.groovy#L37) which verifies this. Moreover, I've checked this in an example [app](https://github.com/platan/handlebars-spring-boot-starter-example/commit/0f50b797fe01a6bbb0229770d22e9763a502741d) using this starter. 
Please compare your application with this simple [example app](https://github.com/platan/handlebars-spring-boot-starter-example/). It uses only two dependencies: `org.springframework.boot:spring-boot-starter-web` and `pl.allegro.tech.boot:handlebars-spring-boot-starter`. 
Which dependencies and in which versions do you use?

**Comment by platan** [comment]
I'm closing this issue since there is no response from @hainesr
