### ISSUE TITLE
Can you help me why my handlebars doesn't work?

### ISSUE THREAD

**Issue by MartianLee** [allegro/handlebars-spring-boot-starter#29]
I was developing my small project with tutorial but I found that my handlebar dependency doesn't work.

here is my build.gradle

```
plugins {
	id 'org.springframework.boot' version '2.1.3.RELEASE'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.greenhair'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compile 'pl.allegro.tech.boot:handlebars-spring-boot-starter:0.3.0'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.h2database:h2'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

and my WebController.java
```
package com.greenhair.spring.web;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

import lombok.AllArgsConstructor;

@Controller
@AllArgsConstructor
public class WebController {

    @GetMapping("/")
    public String main() {
        return "main";
    }
    
    @GetMapping("/test")
    public String test() {
        return "test.html";
    }
}
```

and of course Test doesn't work
```
package com.greenhair.spring.web;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.boot.test.context.SpringBootTest.WebEnvironment.RANDOM_PORT;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = RANDOM_PORT)
public class WebControllerTest {

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    public void MainpageLoading() {
        //when
        String body = this.restTemplate.getForObject("/", String.class);

        //then
        assertThat(body).contains("Spring Boot Web Service");
    }
}
```

and I have main.hbs
```
<!DOCTYPE HTML>
<html>
<head>
    <title>Spring Boot Web Service</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--bootstrap css-->
    <link rel="stylesheet" href="/css/lib/bootstrap.min.css">
</head>
<body>
    <h1>Spring Boot Web Service</h1>

    <div>
     ....

```

I also check gradle `gradle dependencyInsight --configuration compile --dependency pl.allegro.tech.boot:handlebars-spring-boot-starter:0.3.0` And it's perfectly set

But if I enter localhost:8080/
It shows **_"Whitelabel Error Page"_** in '/' But it shows test.html in '/test' so It means template path doesn't applied.
It's really appreciate if somebody give me any kinds of clue T.T

**Comment by platan** [comment]
Hi @MartianLee Where exactly did you put your `main.hbs` file? It should be located in `classpath:templates/` directory (`src/main/resources/templates`). Of course this location can be changed via `handlebars.prefix` property https://github.com/allegro/handlebars-spring-boot-starter#configuration. 
If it doesn't help please share your whole project as a repository, it would be easier to spot the problem.

**Comment by MartianLee** [comment]
Thank you @platan for nice advice !!! 
I put `main.hbs` file into `src/main/resources/templates` sadly doesn't work...
and tried to put configuration on `src/main/resources/application.yml`
Here is my repository. [https://github.com/MartianLee/first-springboot](url)

Thank you for your help again.

**Comment by MartianLee** [comment]
Oh I mean it's still doesn't work. Did you figure out something?

**Comment by platan** [comment]
@MartianLee please change 
```java
    @GetMapping("/")
    public String main() {
        return "main.hbs";
    }
```
to
```java
    @GetMapping("/")
    public String main() {
        return "main";
    }
```
It should work (it works for me).

**Comment by MartianLee** [comment]
Thank you so much. I found that my **java version** was messed up T.T
I found that java version and libraries's version are really relative.
Thank you for your warm suggestion.

**Comment by platan** [comment]
I'm closing the issue. Please let us know if you have any problems.
