### ISSUE TITLE
Asset Pipeline Support?

### ISSUE THREAD

**Issue by drdamour** [allegro/handlebars-spring-boot-starter#30]
have you thought about adding any asset pipeline support?

IE i use frontend-maven-plugin to get compiled assets over to my spring-boot/resources/static directory, but hashed or split thru rollup.

I want hbs to be able to reference these by their base name and have it auto expand to the hash thing...i know thymeleaf has some support for this https://spring.io/blog/2014/07/24/spring-framework-4-1-handling-static-web-resources

wondering if you had considered it or done something similar?

**Comment by platan** [comment]
We do not plans to add support for asset pipeline. This project is not actively developed by our company recently. Last changes were made by the external contributors. 

Have you tried 
https://github.com/bertramdev/asset-pipeline/tree/master/handlebars-asset-pipeline?

**Comment by rougou** [comment]
Yeh lolomp
