### ISSUE TITLE
Rename starter

### ISSUE THREAD

**Issue by snicoll** [allegro/handlebars-spring-boot-starter#4]
Hi,

I am a member of the Spring Boot team and I've just noticed this project. Please rename your starter to not use the `spring-boot-starter` namespace that is reserved for official starters. 

I'd suggest `handlebars-spring-boot-starter`

Thanks!

**Comment by plesiecki** [comment]
Hi,

Thanks for stopping by and pointing it out. Sure, I'm going to rename whole thing. Btw, please let me know if you'd consider taking a pull request to spring-boot.

Thank you for your consideration on this matter.

**Comment by snicoll** [comment]
Hello,

To be honest I don't know. I'd rather have it live here and see how it goes.

BTW, I had a closer look and I saw that you are using `spring.handlebars` as configuration prefix. Please don't use the `sring.*` prefix either as it is reserved as well.

Some more feedback:
- I wouldn't use a prefix too lengthy so `viewResolver` can be renamed to something in a single  word maybe?
- You should enable the annotation processor in your build (`spring-boot-configuration-processor`) so that the relevant meta-data  are generated for IDE support

Let me know if I can help.

**Comment by plesiecki** [comment]
Thanks for your all feedback again. I'm not sure if I should also rename repository or maybe I can leave it as it is. Could you please explain how it's supposed to be in this case?

**Comment by wendigo** [comment]
I personally think that the project name (artefact name) should be consistent with repo name.

**Comment by plesiecki** [comment]
I totally agree with you ;)

**Comment by snicoll** [comment]
I would rename the repo as well, yes.
