### ISSUE TITLE
Upgrade to Handlebars 4.3.x to be java 17 compatible

### ISSUE THREAD

**Issue by J4ken** [allegro/handlebars-spring-boot-starter#47]
Suggestion to update handlebars to 4.3.x to be compatible with java 17.

https://github.com/swagger-api/swagger-codegen/issues/10966
According to this thread, this version should solve the java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Collections$EmptyMap.isEmpty() accessible exception

**Comment by KKolej** [comment]
@J4ken  thanks for this suggestion, We are open for PR to this project, Are You interested in ? 
If You will need help we can help You with this issue.

**Comment by 3750** [comment]
@J4ken we just released https://github.com/allegro/handlebars-spring-boot-starter/releases/tag/handlebars-spring-boot-starter-0.5.0 that supports JDK 17.
